# Generated by Django 4.0 on 2021-12-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFMS', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students',
        ),
    ]
